# Generated by Django 5.1.1 on 2024-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_route_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_long_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(max_length=100),
        ),
    ]
